<template>
	<div class="flex flex-col overflow-x-auto">
		<HeaderAlt></HeaderAlt>
		<div class="w-full h-64 bridge2 flex justify-center mt-[90px]"></div>
		<div class="flex flex-col">
			<h2 class="px-24 text-[48px] font-semibold mt-8">Our Transactions</h2>
			<div class="flex px-24 gap-4 underline text-[24px] text-blue-500">
				<a href="#2020" class="">2020</a>
				<a href="#2021" class="">2021</a>
				<a href="#2022" class="">2022</a>
			</div>
		</div>
		<h3 id="2023" class="px-24 mt-8 text-[32px] font-semibold">2023</h3>
		<div class="px-10 py-8 w-full flex flex-wrap gap-4 overflow-x-auto">
			<article
				v-for="item in tombstones2023.slice().reverse()"
				:id="item.id"
				class="min-w-[18rem] px-8 py-4 glass2 flex flex-col items-center gap-2 text-black h-min"
			>
				<div class="w-36 h-32 flex items-center justify-center">
					<img class="w-fit" :src="item.img" alt="Company Logo" />
				</div>
				<h4 class="text-[24px]">${{ item.amount.toLocaleString("en-US") }}</h4>
				<p class="text-[16px]">{{ item.type }}</p>
				<div class="flex items-center mt-2 gap-4">
					<p class="tag text-[14px]">{{ item.finder }}</p>
					<p class="text-[16px]">
						{{
							item.date.toLocaleDateString("default", {
								month: "long",
								year: "numeric",
							})
						}}
					</p>
				</div>
			</article>
		</div>
		<h3 id="2022" class="px-24 pt-[90px] mt-[-64px] text-[32px] font-semibold">
			2022
		</h3>
		<div class="px-10 py-8 flex flex-wrap gap-4 justify-center">
			<article
				v-for="item in tombstones2022.slice().reverse()"
				class="min-w-[18rem] px-8 py-4 glass2 flex flex-col items-center gap-2 text-black h-min"
			>
				<div class="w-36 h-32 flex items-center justify-center">
					<img class="w-fit max-h-[100%]" :src="item.img" alt="Company Logo" />
				</div>
				<h4 class="text-[24px]">${{ item.amount.toLocaleString("en-US") }}</h4>
				<p class="text-[16px]">{{ item.type }}</p>
				<div class="flex items-center mt-2 gap-4">
					<p class="tag text-[14px]">{{ item.finder }}</p>
					<p class="text-[16px]">
						{{
							item.date.toLocaleDateString("default", {
								month: "long",
								year: "numeric",
							})
						}}
					</p>
				</div>
			</article>
		</div>
		<h3 id="2021" class="px-24 pt-[90px] mt-[-64px] text-[32px] font-semibold">
			2021
		</h3>
		<div
			class="justify-center px-10 py-8 w-full flex flex-wrap gap-4 overflow-x-auto"
		>
			<article
				v-for="item in tombstones2021.slice().reverse()"
				class="min-w-[18rem] px-8 py-4 glass2 flex flex-col items-center gap-2 text-black h-min"
			>
				<div class="w-36 h-32 flex items-center justify-center">
					<img class="w-fit" :src="item.img" alt="Company Logo" />
				</div>
				<h4 class="text-[24px]">${{ item.amount.toLocaleString("en-US") }}</h4>
				<p class="text-[16px]">{{ item.type }}</p>
				<div class="flex items-center mt-2 gap-4">
					<p class="tag text-[14px]">{{ item.finder }}</p>
					<p class="text-[16px]">
						{{
							item.date.toLocaleDateString("default", {
								month: "long",
								year: "numeric",
							})
						}}
					</p>
				</div>
			</article>
		</div>
		<h3 id="2020" class="px-24 pt-[90px] mt-[-64px] text-[32px] font-semibold">
			2020
		</h3>
		<div
			class="px-10 py-8 w-full flex flex-wrap gap-4 justify-center overflow-x-auto"
		>
			<article
				v-for="item in tombstones2020.slice().reverse()"
				class="min-w-[18rem] px-8 py-4 glass2 flex flex-col items-center gap-2 text-black h-min"
			>
				<div class="w-36 h-32 flex items-center justify-center">
					<img class="w-fit" :src="item.img" alt="Company Logo" />
				</div>
				<h4 class="text-[24px]">${{ item.amount.toLocaleString("en-US") }}</h4>
				<p class="text-[16px]">{{ item.type }}</p>
				<div class="flex items-center mt-2 gap-4">
					<p class="tag text-[14px]">{{ item.finder }}</p>
					<p class="text-[16px]">
						{{
							item.date.toLocaleDateString("default", {
								month: "long",
								year: "numeric",
							})
						}}
					</p>
				</div>
			</article>
		</div>
	</div>
</template>

<script>
export default {
	data() {
		return {
			tombstones2023: [],
			tombstones2022: [
				{
					img: "/companyLogos/brewbilt.png",
					amount: 100000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2022"),
				},
				{
					img: "/companyLogos/blackbird.png",
					amount: 130500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 112500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 110700,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/electromedical.png",
					amount: 806400,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/gzbg.png",
					amount: 158400,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/nightfood.png",
					amount: 644000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/smartmetric.png",
					amount: 275400,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/amih.png",
					amount: 56025,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/aitox.png",
					amount: 675000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 58500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/brookmount.png",
					amount: 50001,
					type: "Equity",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 260000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/digerati.png",
					amount: 165000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/electromedical.png",
					amount: 160000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/gah.png",
					amount: 55800,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/marijuana.png",
					amount: 92000,
					type: "Equity",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/1847.png",
					amount: 600000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 80000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 125000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 143250,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/carbonmeta.png",
					amount: 50000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/eari.png",
					amount: 840000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/kisses.png",
					amount: 70000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/konagold.png",
					amount: 595000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/greenflower.png",
					amount: 186000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 128500,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/bfyw.png",
					amount: 310000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 53750,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/gah.png",
					amount: 266000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/gzbg.png",
					amount: 836000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/marijuana.png",
					amount: 114000,
					type: "Equity",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/oncotelic.png",
					amount: 335000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 38880,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/amih.png",
					amount: 265950,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/aitox.png",
					amount: 411729,
					type: "Common Stock",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/blackbird.png",
					amount: 346500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/blackbird.png",
					amount: 385000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 63500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/carbonmeta.png",
					amount: 66111,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 750000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/eco.png",
					amount: 300000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/endexx.png",
					amount: 531250,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/goldenstar.png",
					amount: 370000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/growlife.png",
					amount: 750000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 1535061,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 123487,
					type: "Common Stock",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/igi.png",
					amount: 725000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/kisses.png",
					amount: 150000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/mlfb.png",
					amount: 560000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/marijuana.png",
					amount: 1100000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/novaccess.png",
					amount: 1900000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/oncotelic.png",
					amount: 605000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/greenflower.png",
					amount: 175000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/yellowleaf.png",
					amount: 1000000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/tcc.png",
					amount: 1000000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/bfyw.png",
					amount: 310000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/bloomios.png",
					amount: 137500,
					type: "Convertible Promissory Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 425000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/canb.png",
					amount: 150000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 380000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/eari.png",
					amount: 37000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/gzbc.png",
					amount: 693500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/igi.png",
					amount: 296000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/kisses.png",
					amount: 330000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/mlfb.png",
					amount: 560000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/mlfb.png",
					amount: 63000,
					type: "Equity",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/oncotelic.png",
					amount: 250000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/bfyw.png",
					amount: 310000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "",
					amount: 200000000,
					type: "Equity Line of Credit",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/greenflower.png",
					amount: 150000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/victory.png",
					amount: 50000,
					type: "Equity",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/virtual.png",
					amount: 470000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/yuka.png",
					amount: 300000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/bfyw.png",
					amount: 50000,
					type: "Equity",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 83500,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/bloomios.png",
					amount: 172200,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 279000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/brookmount.png",
					amount: 60000,
					type: "Equity",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/canb.png",
					amount: 600000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/carbonmeta.png",
					amount: 55000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/deepgreen.png",
					amount: 375000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/eari.png",
					amount: 36667,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 133280,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/mlfb.png",
					amount: 39900,
					type: "Equity",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/greenflower.png",
					amount: 177500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/smartmetric.png",
					amount: 475000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/smartmetric.png",
					amount: 5000000,
					type: "Equity Line of Credit",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 38880,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/virtual.png",
					amount: 235000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/yuka.png",
					amount: 50000,
					type: "Equity",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 279000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 1168500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 390000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/gah.png",
					amount: 266000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 51000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/igi.png",
					amount: 370000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/iinx.png",
					amount: 500000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/smartmetric.png",
					amount: 475000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 245000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/trutankless.png",
					amount: 385000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 279000,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 140000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 5000000,
					type: "Equity Line of Credit",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/brookmount.png",
					amount: 96000,
					type: "Equity",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/digerati.png",
					amount: 460000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/eco.png",
					amount: 60000,
					type: "Equity",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/warmup.png",
					amount: 350000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/warmup.png",
					amount: 5000000,
					type: "Equity Line of Credit",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 11160,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/iinx.png",
					amount: 500000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/marijuana.png",
					amount: 60000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/smartmetric.png",
					amount: 950000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/sugarmade.png",
					amount: 485000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
			],
			tombstones2021: [
				{
					img: "/companyLogos/abqq.png",
					amount: 34000,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/amih.png",
					amount: 2375000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/bloomios.png",
					amount: 137500,
					type: "Convertible Promissory Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/bloomios.png",
					amount: 275000,
					type: "Senior Secured Convertible Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/eari.png",
					amount: 26250,
					type: "Equity",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/.png",
					amount: 10000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/hollywall.png",
					amount: 305000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 51000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/mycotopia.png",
					amount: 150000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/oncotelic.png",
					amount: 1750000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/greenflower.png",
					amount: 320000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 128450,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/amih.png",
					amount: 2175000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/cannabis.png",
					amount: 157500,
					type: "Equity",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/gah.png",
					amount: 266000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/greenglobe.png",
					amount: 400000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/gzbg.png",
					amount: 1064000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/gzbg.png",
					amount: 10000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/igi.png",
					amount: 448000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/mlfb.png",
					amount: 315000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/oncotelic.png",
					amount: 250000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/utilicraft.png",
					amount: 72000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/utilicraft.png",
					amount: 5000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 122450,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("October 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 1045000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2021"),
				},
				{
					img: "/companyLogos/data443.png",
					amount: 444444,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2021"),
				},
				{
					img: "/companyLogos/sugarmade.png",
					amount: 444000,
					type: "Equity",
					finder: "Finder",
					date: new Date("October 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 276500,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/aitox.png",
					amount: 20000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 111000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/darkpulse.png",
					amount: 25000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/gex.png",
					amount: 155000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 225000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/mycotopia.png",
					amount: 500000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/greenflower.png",
					amount: 825000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 1266667,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 1266667,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 31000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 178000,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/darkpulse.png",
					amount: 6000000,
					type: "Equity",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/eco.png",
					amount: 150000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 1060000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/greenglobe.png",
					amount: 500000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 153000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 400000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 175000,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/bloomios.png",
					amount: 550000,
					type: "Senior Secured Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 140000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/deepgreen.png",
					amount: 100000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 885000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/iinx.png",
					amount: 500000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/lgbtqloyalty.png",
					amount: 250000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/marijuana.png",
					amount: 268750,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/4less.jpg",
					amount: 231000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/eco.png",
					amount: 225000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2021"),
				},
				{
					img: "/companyLogos/ethema.png",
					amount: 230000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2021"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 1185000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2021"),
				},
				{
					img: "/companyLogos/marijuana.png",
					amount: 537500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2021"),
				},
				{
					img: "/companyLogos/trutankless.png",
					amount: 700000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("June 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 400000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/eari.png",
					amount: 116667,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/ethema.png",
					amount: 550000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 555000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 120000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 132000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/lgbtqloyalty.png",
					amount: 150000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/respirerx.png",
					amount: 300000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/tsr.png",
					amount: 300000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/darkpulse.png",
					amount: 1575000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/digerati.png",
					amount: 113000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/eari.png",
					amount: 122444,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 1055000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/gah.png",
					amount: 135000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 150000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 165000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 133500,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/lgbtqloyalty.png",
					amount: 440000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/odysseygroup.png",
					amount: 1050000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 55000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/touchpoint.png",
					amount: 220000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/tsr.png",
					amount: 250000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 250000,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 410000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 1235000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/iinx.png",
					amount: 500000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/simlatus.png",
					amount: 410000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 560000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/touchpoint.png",
					amount: 330330,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/cbd.png",
					amount: 777778,
					type: "Senior Secured Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 240000,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/aitox.png",
					amount: 1050000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 140000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 5000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/simlatus.png",
					amount: 140000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 1650000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/sunhydrogen.png",
					amount: 25000000,
					type: "Equity",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/aitox.png",
					amount: 522500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/boon.png",
					amount: 48000,
					type: "Block Transaction",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 100000,
					type: "Block Transaction",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 243875,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 500000,
					type: "Reg-A Equity Purchase",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/surge.png",
					amount: 250000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/4less.png",
					amount: 50000,
					type: "Reg-A Equity Purchase",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 50000,
					type: "Senior Secured Note",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/trutankless.png",
					amount: 550000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/waternow.png",
					amount: 605000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2021"),
				},
			],
			tombstones2020: [
				{
					img: "/companyLogos/brewbilt.png",
					amount: 30000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 500000,
					type: "Reg-A Equity Purchase",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/cloudcommerce.png",
					amount: 150000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/ethema.png",
					amount: 275000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 404000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 447000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/iinx.png",
					amount: 600000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/simlatus.png",
					amount: 30000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/surge.png",
					amount: 165000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 170000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/bioquest.png",
					amount: 40000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 45900,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("November 2020"),
				},
				{
					img: "/companyLogos/lingeriefighting.png",
					amount: 225000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2020"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 750000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("November 2020"),
				},
				{
					img: "/companyLogos/sunhydrogen.png",
					amount: 700000,
					type: "Equity",
					finder: "Finder",
					date: new Date("November 2020"),
				},
				{
					img: "/companyLogos/4less.jpg",
					amount: 330000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("November 2020"),
				},
				{
					img: "/companyLogos/cbd.png",
					amount: 202300,
					type: "Secured Convertible Note",
					finder: "Finder",
					date: new Date("November 2020"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 55000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/boomernaturals.png",
					amount: 262500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/brainscientific.png",
					amount: 500000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/cloudcommerce.png",
					amount: 600000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/dsg.png",
					amount: 200000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/fomo.jpg",
					amount: 115000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/growlife.png",
					amount: 377602,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/lgbtqloyalty.png",
					amount: 300000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/quadm.png",
					amount: 55000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/quadm.png",
					amount: 55000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/sunhydrogen.png",
					amount: 700000,
					type: "Equity",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/4less.jpg",
					amount: 250000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 157500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/bioquest.png",
					amount: 25000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/brainscientific.png",
					amount: 100000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/dsg.png",
					amount: 455510,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/greenhygienics.png",
					amount: 25000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/growlife.png",
					amount: 750000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/rssv.png",
					amount: 550000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/sunhydrogen.png",
					amount: 300000,
					type: "Equity",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 63000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/amih.png",
					amount: 100000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 100000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/ethema.png",
					amount: 100000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/27health.png",
					amount: 150000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/27health.png",
					amount: 33000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/27health.png",
					amount: 250000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/quadm.png",
					amount: 110000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/reacgroup.png",
					amount: 575000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/rssv.png",
					amount: 55000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 333333,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/trutankless.png",
					amount: 278000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 166500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 10000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/bioquest.png",
					amount: 100000,
					type: "Equity Financing",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 164800,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/digerati.png",
					amount: 275000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/guidedtherapeutics.png",
					amount: 100000,
					type: "Preferred Equity",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/27health.png",
					amount: 150000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/27health.png",
					amount: 33000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/quadm.png",
					amount: 173500,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/quadm.png",
					amount: 50000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/renavotio.png",
					amount: 112000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/surge.png",
					amount: 270000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/waternow.png",
					amount: 447500,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 2000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("June 2020"),
				},
				{
					img: "/companyLogos/quadm.png",
					amount: 220000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2020"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 550000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("June 2020"),
				},
				{
					img: "/companyLogos/surge.png",
					amount: 400000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2020"),
				},
				{
					img: "/companyLogos/trutankless.png",
					amount: 345000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("June 2020"),
				},
				{
					img: "/companyLogos/guidedtherapeutics.png",
					amount: 400000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2020"),
				},
				{
					img: "/companyLogos/27health.png",
					amount: 110000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2020"),
				},
			],
		};
	},
};
</script>

<style>
.tag {
	background: rgb(124, 211, 136);
	padding: 0.15rem 0.5rem;
	border-radius: 1rem;
	color: white;
}
.bridge2 {
	background-image: url("../assets/Street.jpg");
	background-position: center;
	background-size: cover;
}

.test::after {
	content: "";
	flex: auto;
}
</style>
