<template>
	<v-app>
		<HeaderAlt></HeaderAlt>
		<v-main class="px-8 mb-4">
			<div class="h-64 bridge2 -mx-8"></div>
			<div class="max-w-[1440px] mx-auto mt-8">
				<h2 class="text-h2 mt-8">Our Transactions</h2>

				<div class="d-flex gap-2 text-h5 underline text-blue mb-4">
					<a href="#2020" class="">2020</a>
					<a href="#2021" class="">2021</a>
					<a href="#2022" class="">2022</a>
				</div>

				<TransactionDeck
					v-bind:tombstones="tombstones2023"
					year="2023"
				></TransactionDeck>
				<TransactionDeck
					v-bind:tombstones="tombstones2022"
					year="2022"
				></TransactionDeck>
				<TransactionDeck
					v-bind:tombstones="tombstones2021"
					year="2021"
				></TransactionDeck>
				<TransactionDeck
					v-bind:tombstones="tombstones2020"
					year="2020"
				></TransactionDeck>
				<a
					v-if="showArrow"
					href="#"
					class="fixed bottom-8 right-8 flex gap-2 items-center p-2 bg-grey-darken-1 rounded-full"
				>
					<Icon name="carbon:chevron-up" width="48px" height="48px" />
				</a>
			</div>
		</v-main>
		<Footer></Footer>
	</v-app>
</template>

<script>
export default {
	data() {
		return {
			tombstones2023: [],
			tombstones2022: [
				{
					img: "/companyLogos/brewbilt.png",
					amount: 100000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2022"),
				},
				{
					img: "/companyLogos/blackbird.png",
					amount: 130500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 112500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 110700,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/electromedical.png",
					amount: 806400,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/gzbg.png",
					amount: 158400,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/nightfood.png",
					amount: 644000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/smartmetric.png",
					amount: 275400,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2022"),
				},
				{
					img: "/companyLogos/amih.png",
					amount: 56025,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/aitox.png",
					amount: 675000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 58500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/brookmount.png",
					amount: 50001,
					type: "Equity",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 260000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/digerati.png",
					amount: 165000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/electromedical.png",
					amount: 160000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/gah.png",
					amount: 55800,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/marijuana.png",
					amount: 92000,
					type: "Equity",
					finder: "Finder",
					date: new Date("August 2022"),
				},
				{
					img: "/companyLogos/1847.png",
					amount: 600000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 80000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 125000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 143250,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/carbonmeta.png",
					amount: 50000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/eari.png",
					amount: 840000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/kisses.png",
					amount: 70000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/konagold.png",
					amount: 595000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/greenflower.png",
					amount: 186000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2022"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 128500,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/bfyw.png",
					amount: 310000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 53750,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/gah.png",
					amount: 266000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/gzbg.png",
					amount: 836000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/marijuana.png",
					amount: 114000,
					type: "Equity",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/oncotelic.png",
					amount: 335000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 38880,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2022"),
				},
				{
					img: "/companyLogos/amih.png",
					amount: 265950,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/aitox.png",
					amount: 411729,
					type: "Common Stock",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/blackbird.png",
					amount: 346500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/blackbird.png",
					amount: 385000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 63500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/carbonmeta.png",
					amount: 66111,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 750000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/eco.png",
					amount: 300000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/endexx.png",
					amount: 531250,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/goldenstar.png",
					amount: 370000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/growlife.png",
					amount: 750000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 1535061,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 123487,
					type: "Common Stock",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/igi.png",
					amount: 725000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/kisses.png",
					amount: 150000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/mlfb.png",
					amount: 560000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/marijuana.png",
					amount: 1100000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/novaccess.png",
					amount: 1900000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/oncotelic.png",
					amount: 605000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/greenflower.png",
					amount: 175000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/yellowleaf.png",
					amount: 1000000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/tcc.png",
					amount: 1000000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2022"),
				},
				{
					img: "/companyLogos/bfyw.png",
					amount: 310000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/bloomios.png",
					amount: 137500,
					type: "Convertible Promissory Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 425000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/canb.png",
					amount: 150000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 380000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/eari.png",
					amount: 37000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/gzbg.png",
					amount: 693500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/igi.png",
					amount: 296000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/kisses.png",
					amount: 330000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/mlfb.png",
					amount: 560000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/mlfb.png",
					amount: 63000,
					type: "Equity",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/oncotelic.png",
					amount: 250000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/bfyw.png",
					amount: 310000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/ozop.png",
					amount: 200000000,
					type: "Equity Line of Credit",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/greenflower.png",
					amount: 150000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/victory.png",
					amount: 50000,
					type: "Equity",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/virtual.png",
					amount: 470000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/yuka.png",
					amount: 300000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/bfyw.png",
					amount: 50000,
					type: "Equity",
					finder: "Finder",
					date: new Date("April 2022"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 83500,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/bloomios.png",
					amount: 172200,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 279000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/brookmount.png",
					amount: 60000,
					type: "Equity",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/canb.png",
					amount: 600000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/carbonmeta.png",
					amount: 55000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/deepgreen.png",
					amount: 375000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/eari.png",
					amount: 36667,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 133280,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/mlfb.png",
					amount: 39900,
					type: "Equity",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/greenflower.png",
					amount: 177500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/smartmetric.png",
					amount: 475000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/smartmetric.png",
					amount: 5000000,
					type: "Equity Line of Credit",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 38880,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/virtual.png",
					amount: 235000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/yuka.png",
					amount: 50000,
					type: "Equity",
					finder: "Finder",
					date: new Date("March 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 279000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 1168500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 390000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/gah.png",
					amount: 266000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 51000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/igi.png",
					amount: 370000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/iinx.png",
					amount: 500000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/smartmetric.png",
					amount: 475000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 245000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/trutankless.png",
					amount: 385000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("February 2022"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 279000,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 140000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 5000000,
					type: "Equity Line of Credit",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/brookmount.png",
					amount: 96000,
					type: "Equity",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/digerati.png",
					amount: 460000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/eco.png",
					amount: 60000,
					type: "Equity",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/warmup.png",
					amount: 350000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/warmup.png",
					amount: 5000000,
					type: "Equity Line of Credit",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 11160,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/iinx.png",
					amount: 500000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/marijuana.png",
					amount: 60000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/smartmetric.png",
					amount: 950000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
				{
					img: "/companyLogos/sugarmade.png",
					amount: 485000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2022"),
				},
			],
			tombstones2021: [
				{
					img: "/companyLogos/abqq.png",
					amount: 34000,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/amih.png",
					amount: 2375000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/bloomios.png",
					amount: 137500,
					type: "Convertible Promissory Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/bloomios.png",
					amount: 275000,
					type: "Senior Secured Convertible Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/eari.png",
					amount: 26250,
					type: "Equity",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/.png",
					amount: 10000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/hollywall.png",
					amount: 305000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 51000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/mycotopia.png",
					amount: 150000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/oncotelic.png",
					amount: 1750000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/greenflower.png",
					amount: 320000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 128450,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/amih.png",
					amount: 2175000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/cannabis.png",
					amount: 157500,
					type: "Equity",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/gah.png",
					amount: 266000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/greenglobe.png",
					amount: 400000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/gzbg.png",
					amount: 1064000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/gzbg.png",
					amount: 10000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/igi.png",
					amount: 448000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/mlfb.png",
					amount: 315000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/oncotelic.png",
					amount: 250000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/utilicraft.png",
					amount: 72000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/utilicraft.png",
					amount: 5000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("November 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 122450,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("October 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 1045000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2021"),
				},
				{
					img: "/companyLogos/data443.png",
					amount: 444444,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2021"),
				},
				{
					img: "/companyLogos/sugarmade.png",
					amount: 444000,
					type: "Equity",
					finder: "Finder",
					date: new Date("October 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 276500,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/aitox.png",
					amount: 20000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 111000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/darkpulse.png",
					amount: 25000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/gex.png",
					amount: 155000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 225000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/mycotopia.png",
					amount: 500000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/greenflower.png",
					amount: 825000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 1266667,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 1266667,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 31000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("September 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 178000,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/darkpulse.png",
					amount: 6000000,
					type: "Equity",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/eco.png",
					amount: 150000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 1060000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/greenglobe.png",
					amount: 500000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 153000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 400000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 175000,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/bloomios.png",
					amount: 550000,
					type: "Senior Secured Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 140000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/deepgreen.png",
					amount: 100000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 885000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/iinx.png",
					amount: 500000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/lgbtqloyalty.png",
					amount: 250000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/marijuana.png",
					amount: 268750,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/4less.jpg",
					amount: 231000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("July 2021"),
				},
				{
					img: "/companyLogos/eco.png",
					amount: 225000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2021"),
				},
				{
					img: "/companyLogos/ethema.png",
					amount: 230000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2021"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 1185000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2021"),
				},
				{
					img: "/companyLogos/marijuana.png",
					amount: 537500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2021"),
				},
				{
					img: "/companyLogos/trutankless.png",
					amount: 700000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("June 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 400000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/eari.png",
					amount: 116667,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/ethema.png",
					amount: 550000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 555000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 120000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 132000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/lgbtqloyalty.png",
					amount: 150000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/respirerx.png",
					amount: 300000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/tsr.png",
					amount: 300000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("May 2021"),
				},
				{
					img: "/companyLogos/darkpulse.png",
					amount: 1575000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/digerati.png",
					amount: 113000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/eari.png",
					amount: 122444,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 1055000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/gah.png",
					amount: 135000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 150000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 165000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 133500,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/lgbtqloyalty.png",
					amount: 440000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/odysseygroup.png",
					amount: 1050000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 55000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/touchpoint.png",
					amount: 220000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/tsr.png",
					amount: 250000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("April 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 250000,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 410000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/foothills.png",
					amount: 1235000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/iinx.png",
					amount: 500000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/simlatus.png",
					amount: 410000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 560000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/touchpoint.png",
					amount: 330330,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/cbd.png",
					amount: 777778,
					type: "Senior Secured Convertible Note",
					finder: "Finder",
					date: new Date("March 2021"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 240000,
					type: "Convertible Preferred Equity",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/aitox.png",
					amount: 1050000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 140000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 5000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/simlatus.png",
					amount: 140000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 1650000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/sunhydrogen.png",
					amount: 25000000,
					type: "Equity",
					finder: "Finder",
					date: new Date("February 2021"),
				},
				{
					img: "/companyLogos/aitox.png",
					amount: 522500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/boon.png",
					amount: 48000,
					type: "Block Transaction",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/brewbilt.png",
					amount: 100000,
					type: "Block Transaction",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/cgi.png",
					amount: 243875,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 500000,
					type: "Reg-A Equity Purchase",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/surge.png",
					amount: 250000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/4less.jpg",
					amount: 50000,
					type: "Reg-A Equity Purchase",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 50000,
					type: "Senior Secured Note",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/trutankless.png",
					amount: 550000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("January 2021"),
				},
				{
					img: "/companyLogos/waternow.png",
					amount: 605000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("January 2021"),
				},
			],
			tombstones2020: [
				{
					img: "/companyLogos/brewbilt.png",
					amount: 30000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 500000,
					type: "Reg-A Equity Purchase",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/cloudcommerce.png",
					amount: 150000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/ethema.png",
					amount: 275000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 404000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/homebistro.png",
					amount: 447000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/iinx.png",
					amount: 600000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/simlatus.png",
					amount: 30000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/surge.png",
					amount: 165000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/marquie.png",
					amount: 170000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/bioquest.png",
					amount: 40000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("December 2020"),
				},
				{
					img: "/companyLogos/oxys.png",
					amount: 45900,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("November 2020"),
				},
				{
					img: "/companyLogos/lingeriefighting.png",
					amount: 225000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("November 2020"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 750000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("November 2020"),
				},
				{
					img: "/companyLogos/sunhydrogen.png",
					amount: 700000,
					type: "Equity",
					finder: "Finder",
					date: new Date("November 2020"),
				},
				{
					img: "/companyLogos/4less.jpg",
					amount: 330000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("November 2020"),
				},
				{
					img: "/companyLogos/cbd.png",
					amount: 202300,
					type: "Secured Convertible Note",
					finder: "Finder",
					date: new Date("November 2020"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 55000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/boomernaturals.png",
					amount: 262500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/brainscientific.png",
					amount: 500000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/cloudcommerce.png",
					amount: 600000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/dsg.png",
					amount: 200000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/fomo.jpg",
					amount: 115000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/growlife.png",
					amount: 377602,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/lgbtqloyalty.png",
					amount: 300000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/quadm.png",
					amount: 55000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/quadm.png",
					amount: 55000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/sunhydrogen.png",
					amount: 700000,
					type: "Equity",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/4less.jpg",
					amount: 250000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("October 2020"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 157500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/bioquest.png",
					amount: 25000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/brainscientific.png",
					amount: 100000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/dsg.png",
					amount: 455510,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/greenhygienics.png",
					amount: 25000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/growlife.png",
					amount: 750000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/rssv.png",
					amount: 550000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/sunhydrogen.png",
					amount: 300000,
					type: "Equity",
					finder: "Finder",
					date: new Date("Septemeber 2020"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 63000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/amih.png",
					amount: 100000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 100000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/ethema.png",
					amount: 100000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/27health.png",
					amount: 150000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/27health.png",
					amount: 33000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/27health.png",
					amount: 250000,
					type: "Convertible Preferred",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/quadm.png",
					amount: 110000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/reacgroup.png",
					amount: 575000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/rssv.png",
					amount: 55000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 333333,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/trutankless.png",
					amount: 278000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("August 2020"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 166500,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/abqq.png",
					amount: 10000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/bioquest.png",
					amount: 100000,
					type: "Equity Financing",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 164800,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/digerati.png",
					amount: 275000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/guidedtherapeutics.png",
					amount: 100000,
					type: "Preferred Equity",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/27health.png",
					amount: 150000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/27health.png",
					amount: 33000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/quadm.png",
					amount: 173500,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/quadm.png",
					amount: 50000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/renavotio.png",
					amount: 112000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/surge.png",
					amount: 270000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/waternow.png",
					amount: 447500,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("July 2020"),
				},
				{
					img: "/companyLogos/cety.png",
					amount: 2000000,
					type: "Equity Line Of Credit",
					finder: "Finder",
					date: new Date("June 2020"),
				},
				{
					img: "/companyLogos/quadm.png",
					amount: 220000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2020"),
				},
				{
					img: "/companyLogos/simplicity.png",
					amount: 550000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("June 2020"),
				},
				{
					img: "/companyLogos/surge.png",
					amount: 400000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2020"),
				},
				{
					img: "/companyLogos/trutankless.png",
					amount: 345000,
					type: "Amortizing Convertible Note",
					finder: "Finder",
					date: new Date("June 2020"),
				},
				{
					img: "/companyLogos/guidedtherapeutics.png",
					amount: 400000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2020"),
				},
				{
					img: "/companyLogos/27health.png",
					amount: 110000,
					type: "Convertible Note",
					finder: "Finder",
					date: new Date("June 2020"),
				},
			],
			showArrow: false,
		};
	},
	mounted() {
		window.addEventListener("scroll", this.onScroll);
	},
	beforeUnmount() {
		window.removeEventListener("scroll", this.onScroll);
	},
	methods: {
		onScroll() {
			const firstViewportHeight = window.innerHeight * 0.9;
			const scrollPosition = window.scrollY;
			this.showArrow = scrollPosition >= firstViewportHeight;
		},
	},
};
</script>

<style>
.tag {
	background: rgb(124, 211, 136);
	padding: 0.15rem 0.5rem;
	border-radius: 1rem;
	color: white;
}
.bridge2 {
	background-image: url("../assets/exchange.jpg");
	background-position: 50% 40%;
	background-size: cover;
}

.test::after {
	content: "";
	flex: auto;
}
</style>
